// stuff
export const RECEIVE_STUFF = 'RECEIVE_STUFF'

// edit
export const EDIT_MODE_ENABLED = 'EDIT_MODE_ENABLED'
export const EDIT_MODE_DISABLED = 'EDIT_MODE_DISABLED'

// maps
export const MAPS_LOADED = 'MAPS_LOADED'
export const MAP_CREATED = 'MAP_CREATED'
export const MAP_DELETED = 'MAP_DELETED'

// stories
export const STORIES_LOADED = 'STORIES_LOADED'
export const STORY_CREATED = 'STORY_CREATED'
export const STORY_UPDATED = 'STORY_UPDATED'
export const STORY_DELETED = 'STORY_DELETED'

// pois
export const POIS_LOADED = 'POIS_LOADED'
export const POI_CREATED = 'POI_CREATED'
export const POI_UPDATED = 'POI_UPDATED'
export const POI_DELETED = 'POI_DELETED'

// poi form
export const POI_FORM_INPUT_CHANGED = 'POI_FORM_INPUT_CHANGED'
export const POI_FORM_STORY_ID_TOGGLED = 'POI_FORM_STORY_ID_TOGGLED'
export const POI_FORM_LINK_ADDED = 'POI_FORM_LINK_ADDED'
export const POI_FORM_LINK_REMOVED = 'POI_FORM_LINK_REMOVED'
export const POI_FORM_LINK_MODIFIED = 'POI_FORM_LINK_MODIFIED'
export const POI_FORM_MEDIA_ADDED = 'POI_FORM_MEDIA_ADDED'
export const POI_FORM_MEDIA_REMOVED = 'POI_FORM_MEDIA_REMOVED'
