// stuff
export const RECEIVE_STUFF = 'RECEIVE_STUFF'

// edit
export const EDIT_MODE_ENABLED = 'EDIT_MODE_ENABLED'
export const EDIT_MODE_DISABLED = 'EDIT_MODE_DISABLED'
export const STORIES_LOADED = 'STORIES_LOADED'
export const STORIES_BY_ID_LOADED = 'STORIES_BY_ID_LOADED'
export const STORY_CREATED = 'STORY_CREATED'
export const STORY_EDITED = 'STORY_EDITED'
export const STORY_DELETED = 'STORY_DELETED'
