// stuff
export const RECEIVE_STUFF = 'RECEIVE_STUFF'

// auth
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

// edit
export const EDIT_MODE_ENABLED = 'EDIT_MODE_ENABLED'
export const EDIT_MODE_DISABLED = 'EDIT_MODE_DISABLED'

// maps
export const MAPS_LOADED = 'MAPS_LOADED'
export const MAP_CREATED = 'MAP_CREATED'
export const MAP_DELETED = 'MAP_DELETED'
export const MAP_SELECTED = 'MAP_SELECTED'

// stories
export const STORIES_LOADED = 'STORIES_LOADED'
export const STORY_CREATED = 'STORY_CREATED'
export const STORY_UPDATED = 'STORY_UPDATED'
export const STORY_DELETED = 'STORY_DELETED'
export const STORY_SELECTED = 'STORY_SELECTED'

// pois
export const POIS_LOADED = 'POIS_LOADED'
export const POI_CREATED = 'POI_CREATED'
export const POI_UPDATED = 'POI_UPDATED'
export const POI_DELETED = 'POI_DELETED'
export const POI_SELECTED = 'POI_SELECTED'
export const NEXT_POI_IN_STORY_SET = 'NEXT_POI_IN_STORY_SET'
export const PREVIOUS_POI_IN_STORY_SET = 'PREVIOUS_POI_IN_STORY_SET'

// poi form
export const POI_FORM_INPUT_CHANGED = 'POI_FORM_INPUT_CHANGED'
export const POI_FORM_STORY_ID_TOGGLED = 'POI_FORM_STORY_ID_TOGGLED'
export const POI_FORM_LINK_ADDED = 'POI_FORM_LINK_ADDED'
export const POI_FORM_LINK_REMOVED = 'POI_FORM_LINK_REMOVED'
export const POI_FORM_LINK_MODIFIED = 'POI_FORM_LINK_MODIFIED'
export const POI_FORM_MEDIA_ADDED = 'POI_FORM_MEDIA_ADDED'
export const POI_FORM_MEDIA_REMOVED = 'POI_FORM_MEDIA_REMOVED'
export const NEW_POI_CREATION_STARTED = 'NEW_POI_CREATION_STARTED'

// sidebar
export const SIDEBAR_TOGGLED = 'SIDEBAR_TOGGLED'
export const STORY_FORM_SET_SHOW = 'STORY_FORM_SET_SHOW'
export const STORY_FORM_SET_HIDE = 'STORY_FORM_SET_HIDE'
export const EDITING_STORY_ID_SET = 'EDITING_STORY_ID_SET'
export const STORY_NAME_INPUT_UPDATED = 'STORY_NAME_INPUT_UPDATED'
